// Mock utilities
export const mockDelay = (min = 200, max = 800) =>
  new Promise(resolve => setTimeout(resolve, Math.random() * (max - min) + min))

export const mockExportDelay = () => mockDelay(1000, 3000)

export const mockPaginate = (list, page = 1, size = 20) => {
  const total = list.length
  const start = (page - 1) * size
  const end = start + size
  return {
    records: list.slice(start, end),
    total,
    page,
    size
  }
}

export const createMockBlob = (filename) => {
  const content = `This is a mock file: ${filename}\n\nGenerated by MSW Mock Service Worker`
  return new Blob([content], { type: 'application/octet-stream' })
}
